* ATP-Weltrangliste Herren ( Stand 13.3.1989 )
TESTST:
                DXSET 14,0
                DX.B 'IVAN LENDL'
                DC.W 19424
                DX.B 'M. WILANDER'
                DC.W 18229
                DX.B 'BORIS BECKER'
                DC.W 14637
                DX.B 'ANDRE AGASSI'
                DC.W 14375
                DX.B 'STEFAN EDBERG'
                DC.W 13952
                DX.B 'JOHN MCENROE'
                DC.W 10919
                DX.B 'KENT CARLSSON'
                DC.W 10771
                DX.B 'J. CONNORS'
                DC.W 9472
                DX.B 'JAKOB HLASEK'
                DC.W 9413
                DX.B 'TIM MAYOTTE'
                DC.W 8685
                DX.B 'HENRI LECONTE'
                DC.W 8277
                DX.B 'THOMAS MUSTER'
                DC.W 7713
                DX.B 'M. MECIR'
                DC.W 7306
                DX.B 'G. P.ROLDAN'
                DC.W 6881
                DX.B 'A. KRICKSTEIN'
                DC.W 6771
                DX.B 'BRAD GILBERT'
                DC.W 6490
                DX.B 'E. SANCHEZ'
                DC.W 6464
                DX.B 'YANNICK NOAH'
                DC.W 5792
                DX.B 'J. SVENSSON'
                DC.W 5618
                DX.B 'KEVIN CURREN'
                DC.W 5504
                DX.B 'M. PERNFORS'
                DC.W 5452
                DX.B 'ANDRES GOMEZ'
                DC.W 5418
                DX.B 'A. MANSDORF'
                DC.W 5296
                DX.B 'DARREN CAHILL'
                DC.W 5139
                DX.B 'MICHAEL CHANG'
                DC.W 4900
                DX.B 'RONALD AGENOR'
                DC.W 4508
                DX.B 'S. ZIVOJINOVI'
                DC.W 4505
                DX.B 'ANDERS JARRYD'
                DC.W 4480
                DX.B 'A. CHESNOKOV'
                DC.W 4400
                DX.B 'DAN GOLDIE'
                DC.W 4288
                DX.B 'GUY FORGET'
                DC.W 3800
                DX.B 'A. VOLKOV'
                DC.W 3786
                DX.B 'JOHAN KRIEK'
                DC.W 3742
                DX.B 'JORDI ARRESE'
                DC.W 3696
                DX.B 'D. ROSTAGNO'
                DC.W 3577
                DX.B 'M. WOODFORDE'
                DC.W 3545
                DX.B 'P. ANNACONE'
                DC.W 3536
                DX.B 'C. RENSBURG'
                DC.W 3520
                DX.B 'JAY BERGER'
                DC.W 3464
                DX.B 'HORST SKOFF'
                DC.W 3463
                DX.B 'J. FITZGERALD'
                DC.W 3425
                DX.B 'WALLY MASUR'
                DC.W 3260
                DX.B 'JIM COURIER'
                DC.W 3237
                DX.B 'A. MANCINI'
                DC.W 3214
                DX.B 'M. GUSTAFSSON'
                DC.W 3169
                DX.B 'LUIZ MATTAR'
                DC.W 3152
                DX.B 'BRUNO ORESAR'
                DC.W 3101
                DX.B 'ROBERT SEGUSO'
                DC.W 2986
                DX.B 'R. KRISHNAN'
                DC.W 2960
                DX.B 'M. FILIPPINI'
                DC.W 2803
                DX.B 'PAT CASH'
                DC.W 2794
                DX.B 'MARTIN JAITE'
                DC.W 2781
                DX.B 'J. GUNARSSON'
                DC.W 2771
                DX.B 'P. LUNDGREN'
                DC.W 2770
                DX.B 'C. BERGSTROM'
                DC.W 2739
                DX.B 'P. KUEHNEN'
                DC.W 2714
                DX.B 'JAIME YZAGA'
                DC.W 2695
                DX.B 'H. DE LA PENA'
                DC.W 2667
                DX.B 'L. LAVALLE'
                DC.W 2589
                DX.B 'MILAN SREJBER'
                DC.W 2578
                DX.B 'LAWSON DUNCAN'
                DC.W 2567
                DX.B 'ERIC JELEN'
                DC.W 2567
                DX.B 'S. MATSUOKA'
                DC.W 2484
                DX.B 'FERNANDO LUNA'
                DC.W 2472
